In [3]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [5]:
#Archivo de mi ciudad
df= pd.read_csv('Mexico_city.csv')
df

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,1698274831948209016,Roma Residence | Luxury Suite 305,471105419,1.470125e+18,Manuel,NaN,Cuauhtémoc,19.406572,-99.163091,Entire home/apt,2066.0,1.0,0,NaN,NaN,42,365,0,NaN
1,1120444645818769896,Grande y bonita habitación con cocina y baño,548898239,1.470455e+18,Catu,NaN,Benito Juárez,19.394448,-99.163367,Entire home/apt,628.0,1.0,0,NaN,NaN,1,257,0,NaN
2,1414477907775396874,Ven a sentirte como en casa.,49281983,1.465751e+18,Mireya,NaN,Coyoacán,19.339362,-99.185070,Private room,499.0,1.0,0,NaN,NaN,2,158,0,NaN
3,1298027147444763745,Habitación pequeña 16,368484187,1.469744e+18,Gerardo,NaN,Miguel Hidalgo,19.461230,-99.190020,Private room,2511.0,1.0,0,NaN,NaN,2,365,0,NaN
4,1680714857095865427,Quadruple Suite with Bathroom,1680682785801540826,1.680683e+18,Halinka,NaN,Cuauhtémoc,19.420992,-99.157935,Private room,8263.0,1.0,0,NaN,NaN,2,365,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31425,1668513782034090561,Habitación privada excelente ubicación Buenavista,741668723,1.668514e+18,Kevin,NaN,Cuauhtémoc,19.448000,-99.150580,Private room,933.0,1.0,0,NaN,NaN,1,365,0,NaN
31426,1694398175149004981,Hab 3. Friends&fam cama+clóset y áreas comunes,1685078163776089732,1.685079e+18,Marie,NaN,Cuauhtémoc,19.407100,-99.163030,Private room,707.0,4.0,0,NaN,NaN,5,364,0,NaN
31427,1694382707868744808,"Habitación 1. Matrimonial, clóset, tocador y sofa",1685078163776089732,1.685079e+18,Marie,NaN,Cuauhtémoc,19.407580,-99.162510,Private room,1061.0,4.0,0,NaN,NaN,5,364,0,NaN
31428,1618288599296526432,P2 Alojamiento pequeño con cocina,739884792,1.604570e+18,Jorge GA,NaN,Venustiano Carranza,19.437680,-99.088620,Entire home/apt,NaN,2.0,0,NaN,NaN,7,0,0,NaN
31429,1133689320452555924,Departamento en la Juárez,502955535,1.470261e+18,Chio,NaN,Cuauhtémoc,19.427920,-99.153700,Entire home/apt,1250.0,60.0,19,2025-04-29,0.77,1,186,0,NaN

In [6]:
#Confirman info. de DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31430 entries, 0 to 31429
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              31430 non-null  int64
 1   name                            31430 non-null  str
 2   host_id                         31430 non-null  int64
 3   host_profile_id                 31426 non-null  float64
 4   host_name                       31425 non-null  str
 5   neighbourhood_group             0 non-null      float64
 6   neighbourhood                   31430 non-null  str
 7   latitude                        31430 non-null  float64
 8   longitude                       31430 non-null  float64
 9   room_type                       31430 non-null  str
 10  price                           29637 non-null  float64
 11  minimum_nights                  31419 non-null  float64
 12  number_of_reviews               31430 non-null  int64
 13  last_review                     25931 non-null  str
 14  reviews_per_month               25931 non-null  float64
 15  calculated_host_listings_count  31430 non-null  int64
 16  availability_365                31430 non-null  int64
 17  number_of_reviews_ltm           31430 non-null  int64
 18  license                         0 non-null      float64
dtypes: float64(8), int64(6), str(5)
memory usage: 4.6 MB

## FILTROS

**A. Los registros de 5 “host name” diferentes**

In [31]:
# Quitamos los nombres vacíos y repetidos
# y mostramos los primeros 5

filtroA = df.dropna(subset=["host_name"]).drop_duplicates("host_name").head(6)

# Guardamos el resultado
filtroA.to_csv("IncisoA.csv")

# Mostramos el resultado
print(filtroA)

                    id                                          name  \
0  1698274831948209016             Roma Residence | Luxury Suite 305
1  1120444645818769896  Grande y bonita habitación con cocina y baño
2  1414477907775396874                  Ven a sentirte como en casa.
3  1298027147444763745                         Habitación pequeña 16
4  1680714857095865427                 Quadruple Suite with Bathroom
5  1168174173941960570                       Descanso en centro cdmx

               host_id  host_profile_id host_name  neighbourhood_group  \
0            471105419     1.470125e+18    Manuel                  NaN
1            548898239     1.470455e+18      Catu                  NaN
2             49281983     1.465751e+18    Mireya                  NaN
3            368484187     1.469744e+18   Gerardo                  NaN
4  1680682785801540826     1.680683e+18   Halinka                  NaN
5            115584349     1.462908e+18      Abel                  NaN

    neighbourhood   latitude  longitude        room_type   price  \
0      Cuauhtémoc  19.406572 -99.163091  Entire home/apt  2066.0
1   Benito Juárez  19.394448 -99.163367  Entire home/apt   628.0
2        Coyoacán  19.339362 -99.185070     Private room   499.0
3  Miguel Hidalgo  19.461230 -99.190020     Private room  2511.0
4      Cuauhtémoc  19.420992 -99.157935     Private room  8263.0
5      Cuauhtémoc  19.428470 -99.147490     Private room  2283.0

   minimum_nights  number_of_reviews last_review  reviews_per_month  \
0             1.0                  0         NaN                NaN
1             1.0                  0         NaN                NaN
2             1.0                  0         NaN                NaN
3             1.0                  0         NaN                NaN
4             1.0                  0         NaN                NaN
5             1.0                  7  2025-12-21               0.35

   calculated_host_listings_count  availability_365  number_of_reviews_ltm  \
0                              42               365                      0
1                               1               257                      0
2                               2               158                      0
3                               2               365                      0
4                               2               365                      0
5                               2                88                      3

   license
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN

**B. Los registros de los host que se hallan unido a Airbnb “despues del año 2020”**

In [28]:
# Convertimos los datos de last_review a fecha

df['last_review'] = pd.to_datetime(df['last_review'])

# Buscamos las fechas que sean después del año 2020

filtroB = df[df["last_review"] > '31-12-2020']

# Creamos un archivo con los resultados

filtroB.to_csv("IncisoB.csv")

# Vemos el resultado

filtroB

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
5,1168174173941960570,Descanso en centro cdmx,115584349,1.462908e+18,Abel,NaN,Cuauhtémoc,19.428470,-99.147490,Private room,2283.0,1.0,7,2025-12-21,0.35,2,88,3,NaN
6,981382350679584665,Writer Suite in Casa Pani,305540724,1.469564e+18,Casa,NaN,Cuauhtémoc,19.434075,-99.170758,Private room,2238.0,1.0,3,2025-02-13,0.09,6,339,0,NaN
9,1326338399412078934,Casa,44514361,1.465661e+18,Mario,NaN,Álvaro Obregón,19.319470,-99.292490,Entire home/apt,4300.0,2.0,3,2025-06-16,0.19,1,268,1,NaN
12,1547637190139759585,Casa Tarango,93943242,1.467134e+18,Gustavo,NaN,Álvaro Obregón,19.362400,-99.222878,Entire home/apt,1855.0,4.0,5,2026-05-13,1.14,5,241,5,NaN
15,49761795,Habitación compartida al Sur de la CDMX,51452913,1.465805e+18,Jose,NaN,Tlalpan,19.299480,-99.164000,Private room,400.0,1.0,1,2021-06-01,0.02,1,87,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31414,1629321162321342927,Departamento en el corazón de la Roma.,353717923,1.629274e+18,Janet,NaN,Cuauhtémoc,19.420140,-99.159510,Entire home/apt,NaN,2.0,4,2026-05-02,1.07,1,0,4,NaN
31416,1634378954436838884,Roma Norte,15043319,1.462593e+18,Nico,NaN,Cuauhtémoc,19.416740,-99.154960,Entire home/apt,NaN,4.0,3,2026-04-06,0.78,10,0,3,NaN
31417,1635702109729591102,Centric and bright apartment in Escandón,12863633,1.462584e+18,Nicole,NaN,Miguel Hidalgo,19.403680,-99.174920,Entire home/apt,1161.0,4.0,3,2026-06-08,1.84,1,17,3,NaN
31422,1653947682328533178,Recámara 20 mn Estadio azteca\n10mn Zona Hospi...,703248574,1.638756e+18,Pablo Chávez,NaN,Tlalpan,19.285536,-99.168377,Private room,400.0,1.0,2,2026-05-15,1.00,1,336,2,NaN
31429,1133689320452555924,Departamento en la Juárez,502955535,1.470261e+18,Chio,NaN,Cuauhtémoc,19.427920,-99.153700,Entire home/apt,1250.0,60.0,19,2025-04-29,0.77,1,186,0,NaN

**C.Los registros de los host que responden “a más tardar en 1 día”**

In [29]:
# Importamos pandas
import pandas as pd

# Leemos el archivo CSV
df = pd.read_csv("Mexico_city.csv")

# Mostramos las columnas disponibles
print(df.columns)

# La columna 'host_response_time' no existe en mi archivo,
# por lo que no podemos realizar este filtro.

Index(['id', 'name', 'host_id', 'host_profile_id', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='str')

**D. Los registros de las filas “Múltiplos de 200… (400, 600, 800, etc.)”**

In [33]:
# Tomamos una fila cada 200 registros, empezando desde la fila 0
filtroD = df[::200]

# Guardamos los datos en un archivo CSV
filtroD.to_csv("IncisoD.csv")

# Mostramos los resultados
print(filtroD)

                        id                                               name  \
0      1698274831948209016                  Roma Residence | Luxury Suite 305
200     507289029262650672                     Enjoyable 2 bedroom apartament
400    1359556825771303219                   Recámara casa rústica Roma Norte
600    1309003088126476832         Apartment in Roma Norte with mexican style
800    1661017243749208912               Loft nuevo cerca de hospital general
...                    ...                                                ...
30600  1669137104582524802               Departamento de lujo en Alto Polanco
30800  1287678810814853762  Loft with Panoramic View | Gym | Cowork | Reforma
31000  1523941845633221196  Suite céntrica dentro de casa neocolonial vintage
31200             36279589                  Beautiful Lumber Houses at Ajusco
31400  1598811344408728112        Departamento Polanco cerca de Museo Soumaya

         host_id  host_profile_id       host_name  neighbourhood_group  \
0      471105419     1.470125e+18          Manuel                  NaN
200     67744437     1.462775e+18     Maria Adela                  NaN
400     26208786     1.465360e+18            Joel                  NaN
600     36624225     1.465546e+18           Diego                  NaN
800     18062302     1.462605e+18          Esther                  NaN
...          ...              ...             ...                  ...
30600  361255553     1.469725e+18         Rodrigo                  NaN
30800  555991522     1.470483e+18  Mexico Mi Casa                  NaN
31000  529770917     1.463868e+18          Monica                  NaN
31200  272851699     1.463356e+18   Carlos Arturo                  NaN
31400  471027411     1.470124e+18         Junqiao                  NaN

        neighbourhood   latitude  longitude        room_type   price  \
0          Cuauhtémoc  19.406572 -99.163091  Entire home/apt  2066.0
200    Miguel Hidalgo  19.436540 -99.196230  Entire home/apt  2078.0
400        Cuauhtémoc  19.416730 -99.159260     Private room   395.0
600        Cuauhtémoc  19.424493 -99.155460  Entire home/apt  2240.0
800        Cuauhtémoc  19.413497 -99.149090  Entire home/apt  1712.0
...               ...        ...        ...              ...     ...
30600  Miguel Hidalgo  19.441061 -99.182162  Entire home/apt  2549.0
30800  Miguel Hidalgo  19.437348 -99.172069  Entire home/apt  1517.0
31000      Cuauhtémoc  19.410895 -99.133320     Private room   809.0
31200         Tlalpan  19.234070 -99.176070  Entire home/apt     NaN
31400  Miguel Hidalgo  19.445063 -99.203318  Entire home/apt     NaN

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
0                 1.0                  0         NaN                NaN
200               3.0                  0         NaN                NaN
400               2.0                  1  2025-02-25               0.06
600               1.0                 55  2026-06-01               3.17
800               1.0                  1  2026-05-05               0.68
...               ...                ...         ...                ...
30600             1.0                  0         NaN                NaN
30800             2.0                 46  2026-06-01               2.59
31000             3.0                 15  2026-06-05               1.91
31200             1.0                 17  2023-12-25               0.28
31400             3.0                  2  2026-03-18               0.49

       calculated_host_listings_count  availability_365  \
0                                  42               365
200                                 9                19
400                                 1                 3
600                                 1                72
800                                 4               111
...                               ...               ...
30600                               1               284
30800                              16               206
31000                               3               153
31200                               1                40
31400                               6                 0

       number_of_reviews_ltm  license
0                          0      NaN
200                        0      NaN
400                        0      NaN
600                       32      NaN
800                        1      NaN
...                      ...      ...
30600                      0      NaN
30800                     31      NaN
31000                     15      NaN
31200                      0      NaN
31400                      2      NaN

[158 rows x 19 columns]

**E. Los registros de los tipos de cuarto: “Entire home” y “Private room”**

In [34]:
# Seleccionamos los registros que tengan alguno de los dos tipos de habitación
filtroE = df[df["room_type"].isin(["Entire home/apt", "Private room"])]

# Guardamos los resultados en un archivo CSV
filtroE.to_csv("IncisoE.csv")

# Mostramos los resultados
print(filtroE)

                        id                                               name  \
0      1698274831948209016                  Roma Residence | Luxury Suite 305
1      1120444645818769896       Grande y bonita habitación con cocina y baño
2      1414477907775396874                       Ven a sentirte como en casa.
3      1298027147444763745                              Habitación pequeña 16
4      1680714857095865427                      Quadruple Suite with Bathroom
...                    ...                                                ...
31425  1668513782034090561  Habitación privada excelente ubicación Buenavista
31426  1694398175149004981     Hab 3. Friends&fam cama+clóset y áreas comunes
31427  1694382707868744808  Habitación 1. Matrimonial, clóset, tocador y sofa
31428  1618288599296526432                  P2 Alojamiento pequeño con cocina
31429  1133689320452555924                          Departamento en la Juárez

                   host_id  host_profile_id host_name  neighbourhood_group  \
0                471105419     1.470125e+18    Manuel                  NaN
1                548898239     1.470455e+18      Catu                  NaN
2                 49281983     1.465751e+18    Mireya                  NaN
3                368484187     1.469744e+18   Gerardo                  NaN
4      1680682785801540826     1.680683e+18   Halinka                  NaN
...                    ...              ...       ...                  ...
31425            741668723     1.668514e+18     Kevin                  NaN
31426  1685078163776089732     1.685079e+18     Marie                  NaN
31427  1685078163776089732     1.685079e+18     Marie                  NaN
31428            739884792     1.604570e+18  Jorge GA                  NaN
31429            502955535     1.470261e+18      Chio                  NaN

             neighbourhood   latitude  longitude        room_type   price  \
0               Cuauhtémoc  19.406572 -99.163091  Entire home/apt  2066.0
1            Benito Juárez  19.394448 -99.163367  Entire home/apt   628.0
2                 Coyoacán  19.339362 -99.185070     Private room   499.0
3           Miguel Hidalgo  19.461230 -99.190020     Private room  2511.0
4               Cuauhtémoc  19.420992 -99.157935     Private room  8263.0
...                    ...        ...        ...              ...     ...
31425           Cuauhtémoc  19.448000 -99.150580     Private room   933.0
31426           Cuauhtémoc  19.407100 -99.163030     Private room   707.0
31427           Cuauhtémoc  19.407580 -99.162510     Private room  1061.0
31428  Venustiano Carranza  19.437680 -99.088620  Entire home/apt     NaN
31429           Cuauhtémoc  19.427920 -99.153700  Entire home/apt  1250.0

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
0                 1.0                  0         NaN                NaN
1                 1.0                  0         NaN                NaN
2                 1.0                  0         NaN                NaN
3                 1.0                  0         NaN                NaN
4                 1.0                  0         NaN                NaN
...               ...                ...         ...                ...
31425             1.0                  0         NaN                NaN
31426             4.0                  0         NaN                NaN
31427             4.0                  0         NaN                NaN
31428             2.0                  0         NaN                NaN
31429            60.0                 19  2025-04-29               0.77

       calculated_host_listings_count  availability_365  \
0                                  42               365
1                                   1               257
2                                   2               158
3                                   2               365
4                                   2               365
...                               ...               ...
31425                               1               365
31426                               5               364
31427                               5               364
31428                               7                 0
31429                               1               186

       number_of_reviews_ltm  license
0                          0      NaN
1                          0      NaN
2                          0      NaN
3                          0      NaN
4                          0      NaN
...                      ...      ...
31425                      0      NaN
31426                      0      NaN
31427                      0      NaN
31428                      0      NaN
31429                      0      NaN

[31043 rows x 19 columns]

**f) Registros que tengan como máximo 4 camas**

In [41]:
# Inciso F
# No se puede realizar este filtro porque el archivo no cuenta
# con una columna que indique la cantidad de camas.

**H. Los registros de las columnas “impares”**

In [42]:
# Inciso H
# Seleccionamos las columnas que tienen posición impar
filtroH = df.iloc[:, 1::2]

# Guardamos los resultados en un archivo CSV
filtroH.to_csv("IncisoH.csv")

# Mostramos los resultados
print(filtroH)

                                                    name  host_profile_id  \
0                      Roma Residence | Luxury Suite 305     1.470125e+18
1           Grande y bonita habitación con cocina y baño     1.470455e+18
2                           Ven a sentirte como en casa.     1.465751e+18
3                                  Habitación pequeña 16     1.469744e+18
4                          Quadruple Suite with Bathroom     1.680683e+18
...                                                  ...              ...
31425  Habitación privada excelente ubicación Buenavista     1.668514e+18
31426     Hab 3. Friends&fam cama+clóset y áreas comunes     1.685079e+18
31427  Habitación 1. Matrimonial, clóset, tocador y sofa     1.685079e+18
31428                  P2 Alojamiento pequeño con cocina     1.604570e+18
31429                          Departamento en la Juárez     1.470261e+18

       neighbourhood_group   latitude        room_type  minimum_nights  \
0                      NaN  19.406572  Entire home/apt             1.0
1                      NaN  19.394448  Entire home/apt             1.0
2                      NaN  19.339362     Private room             1.0
3                      NaN  19.461230     Private room             1.0
4                      NaN  19.420992     Private room             1.0
...                    ...        ...              ...             ...
31425                  NaN  19.448000     Private room             1.0
31426                  NaN  19.407100     Private room             4.0
31427                  NaN  19.407580     Private room             4.0
31428                  NaN  19.437680  Entire home/apt             2.0
31429                  NaN  19.427920  Entire home/apt            60.0

      last_review  calculated_host_listings_count  number_of_reviews_ltm
0             NaN                              42                      0
1             NaN                               1                      0
2             NaN                               2                      0
3             NaN                               2                      0
4             NaN                               2                      0
...           ...                             ...                    ...
31425         NaN                               1                      0
31426         NaN                               5                      0
31427         NaN                               5                      0
31428         NaN                               7                      0
31429  2025-04-29                               1                      0

[31430 rows x 9 columns]